rules: ["convert_plink", "concat_plink", "build_grm_chunks", "concat_grm_chunks", "greml_gpsm", "snp_effects_gpsm", "single_chrom_grm", "gemma_grm"]

parts: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50"]

run_name: "200910_RAN"

phenotype_dict: {"meantemp_noLSF":"1", "precip_noLSF":"2", "elev_noLSF":"3", "minvap_noLSF":"4", "maxvap_noLSF":"5", "mintemp_noLSF":"6", "maxtemp_noLSF":"7", "dewpoint_noLSF":"8", "latitude_noLSF":"9", "longitude_noLSF":"10"}

phenotypes: ["meantemp_noLSF", "precip_noLSF", "elev_noLSF", "minvap_noLSF", "maxvap_noLSF", "mintemp_noLSF", "maxtemp_noLSF", "dewpoint_noLSF", "latitude_noLSF", "longitude_noLSF"]

phenotype_file: "output/200910_RAN/phenotypes/200910_RAN.environment.txt"

maf: 0.01

grm_threads: 8

greml_threads: 30

gwas_threads: 10

plink_threads: 4

plink_mem: 2000
